### PR TITLE
Spherical RT first cut

### PR DESCRIPTION
**Pull request by jmansour**
* Add `Ex_Stokes_Spherical_RT.py`.
  This model operates correctly, but solver is
  *slow* and serial only.
* Update kd-tree cell finding to index on GAUSS
  or REGULAR swarm layout points.
* Selectively enable/disable mesh hashing for all mesh via PETSc
  options.
* Swarm `populate` routine selects REGULAR for simplex cell
  mesh, and GAUSS otherwise.
* Changed populate parameter from
  `ppcell` to `fill_param`, as `ppcell` is misleading,
  and `fill_param` is what PETSc uses.
* Stripped `dm.setLocalSizes()`  routines from swarm populate method.
  They were setting incorrect values, and there doesn't appear to be
  any overhead in not using them. Further investigation warranted.
* Add further docstrings.

### CODE REVIEW

**Comment by jmansour** [comment]
Hey UW crew! I miss you all very much. 😘

This is just a little model me @julesghub & @dansand started last week that I wanted to finish. Well, it's more a starting point than a finish perhaps, but it works. Which is to say, it appears to be doing what I'd expect, but some qualitative test would be a very good idea. Perhaps some good old growth rate analyses. Also the solve is slow.. very slow, and very serial. Better solver configs shouldn't be too difficult.

The main issue encountered is the inefficiencies in locating swarm particle owning cells. We hit this with any call to `DMLocatePoints()` (via the `swarm.access()` manager for migration), and also where we wish to evaluate (for example) velocities on the particles. I've generalised the kd-tree routines to index on gauss (or regular spaced) points, but even so 5% of the owning cell guesses are incorrect which results in a factor of 100 slow down without mesh hashing (where brute force is used).  For PETSc 3.15, this puts 3D out of reach, but checking 3.16 it appears that @knepley has added the required routines for 3d hashing too, which is great. I'd suggest 3.16 compat is fast-tracked and perhaps set as a min version to ensure usability across the range of models you guys will be wanting to do.

**Comment by knepley** [comment]
@jmansour Looking above, I wanted to point out that we also have nice quadratures for simplices (Stroud) here: https://gitlab.com/petsc/petsc/-/blob/main/src/dm/dt/interface/dt.c#L1931 in case you wanted the partner to GAUSS.

**Comment by jmansour** [comment]
Thanks @knepley

For the above, I'm only talking about the layout for populating swarm particles and for nearest neighbour indexing. We don't set anything specific for the assembly quadratures, so should pickup whatever PETSc defaults to, which I assume should be optimal right?

**Comment by knepley** [comment]
We default to this for PetscQuadrature, so you should be fine.

**Pull request merged**
