### PR TITLE
JOSS paper / simplification

### PR DESCRIPTION
**Pull request by lmoresi**
Push the JOSS paper changes. Simplification of the repository.

Also fixing a moving-mesh bug !

L

### CODE REVIEW

**Review by julesghub — COMMENTED** [review]
I approve all.

**Comment by lmoresi** [comment]
You're no John Mansour ...

**Review by julesghub — APPROVED** [review]

**Comment by lmoresi** [comment]
Can you merge @julesghub - I'm boarding a plane in a sec.

**Comment by julesghub** [comment]
Merged, bon voyage el diablo!

**Pull request merged**
