### PR TITLE
Sympy meets PETSc pointwise fns - refactored

### PR DESCRIPTION
**Pull request by lmoresi**
This PR has a refactor of the sympy interface to the PETSc pointwise functions which produces Jacobians completely via sympy diff (using derive_by_array, mostly). 

There are two generic classes for scalar problems and vector / saddle point problems. Other solvers derive from that. Notation is as close as possible to the Knepley et al Unified Residual paper (Arxiv). 

This is still a work in progress ... but I am happy that the complexity of sympy / JIT / SNES looks like it can disappear into the background and just do its thing.

### CODE REVIEW

**Comment by lmoresi** [comment]
Files to focus on for this PR are the solvers.pyx ( specific equation systems)  and generic_solvers.pyx (abstract and based on the unified residuals paper).

@knepley, @jmansour - I think this could be more elegant if we could directly use the output of the derive_by_array routines in the JIT functions, but the indexing is off. Still, with the paper in one hand and the code in the other, this feels like quite a good correspondence between code and theory.

```
        F0  = sympy.Array((self._UF0.to_matrix(self.mesh.N))[0:dim])
        F1  = sympy.Array(self._UF1)

        # ... stuff 

        ## Using sympy ARRAY which should generalize well
        ## but has some issues with the change in ordering in petsc v. sympy.
        ## so we will leave both here to compare across a range of problems.

        G0 = sympy.derive_by_array(F0, self._U)
        G1 = sympy.derive_by_array(F0, self._L)
        G2 = sympy.derive_by_array(F1, self._U)
        G3 = sympy.derive_by_array(F1, self._L)

        ## Less elegant
        # reorganise indices from sympy to petsc ordering / reshape to Matrix form

        self._uu_G0 = sympy.ImmutableMatrix(G0)
        self._uu_G1 = sympy.ImmutableMatrix(sympy.permutedims(G1, (2,1,0)  ).reshape(dim,dim*dim))
        self._uu_G2 = sympy.ImmutableMatrix(sympy.permutedims(G2, (2,1,0)  ).reshape(dim*dim,dim))
        self._uu_G3 = sympy.ImmutableMatrix(sympy.permutedims(G3, (3,1,2,0)).reshape(dim*dim,dim*dim))

```

**Comment by knepley** [comment]
This is amazing. I have been wanting this for years. To me it looks like they put the components on the outside, which might be better for vectorization (I am never good at that). Is that what the reordering is?

**Comment by jmansour** [comment]
I've only had a chance to have a cursory skim, but looks like you've done a great job generalising the implementation @lmoresi ! You've been hacking code like a mad-man. 🙂

I'll pull it down on the weekend and have closer look.

**Comment by lmoresi** [comment]
> This is amazing. I have been wanting this for years. To me it looks like they put the components on the outside, which might be better for vectorization (I am never good at that). Is that what the reordering is?

Thanks @knepley ... it took me a while to see the simplicity in the formulation but, having had a play with it, I am amazed at how flexible it is when combined with symbolic algebra code. I guess we should write this up with some interesting examples. We are overdue a paper !

As for the re-ordering ... I noticed a couple of times that indices were transposed from what I would normally expect (e.g. in defining the gradients of vectors) and it only gets worse with the fourth order tensors. But, in a future iteration, perhaps we can handle the arrays directly and fix the ordering behind the scenes, once and for all.

**Comment by knepley** [comment]
I am definitely on board for a paper. We can mix in the new adaptive mesh refinement :)

**Pull request merged**
