### PR TITLE
Alpha release 0.4

### PR DESCRIPTION
**Pull request by lmoresi**
I found / fixed (maybe) an annoying parallel regression, and added some very light parallel tests (not automated with pytest). 

I also tried to simplify the constitutive law interface a little bit and made sure the solvers all reset when changes are made to the material properties. This seems to work now.

Also flicked the switch to make discontinuous variables use points within the element. This is mostly for the swarm proxy variables which are set-up using the kdtree so overlapping points in the global domain cause trouble. 

tests passing, more examples fixed up but not all of them.

### CODE REVIEW

**Review by julesghub — COMMENTED** [review]
Nice @lmoresi!
CHANGES.md needs some work.
And what is AdvDiffusionSwarm?

**Comment by lmoresi** [comment]
> 

Indeed - I did not see that changes file before so now there is quite a bit of catching up to do.

The AdvectionDiffusionSWARM is supposed to be the exact counterpart of the AdvectionDiffusionSLCN example that switches out the other equivalent solver. However, at the moment, the swarm advection routines seem to fail in this example. It has the makings of a good test problem. 

(SLCN - sets up a swarm on the node points and advects backwards to calculate T* as in the SLCN recipe. The swarm version projects T* from the swarm-variable).

**Comment by lmoresi** [comment]
Quite a bit of tidying of the submodules for:
  - CoordinateSystems: making those more logical. There is a "base" coordinate system which is the one on the DM and there are "Natural" Coordinates and Cartesian Coordinates. If the DM is cartesian then the Base and the Cartesian forms are the same and the Natural coordinates (if relevant) are defined symbolically in terms of the Natural Coordinates. If the DM has cylindrical coords then its the opposite. In the end, using the Natural system is a reasonable strategy for the user.
  -  Example of how to set up meshes with non-Cartesian coords. Given the above comments, there is not much difference in the setup of the code. Just that the boundary conditions are straightforward compared to the penalty approach we use in the Cartesian case.
  - This is not bug free ... there are still issues with Jacobians (of course) and so forth. Maybe I just missed some things.

**Comment by lmoresi** [comment]
It turns out that there are some built in assumptions with function evaluations about the basis vectors that are used and these do not work well in situations where those basis vectors are different for multiple meshes in a model. See the simple (WIP) example of cylindrical Stokes that has both Cartesian and Cylindrical formulations in the same script (to compare the results). 

So I have renamed the basis vectors so each mesh has a unique set and I had to make a few fixes in the function evaluation to make sure these did not get muddled up. Usually this is not visible to a user because it is masked by the LaTeX representation in the notebook. What is visible is that we have to have a coordinate system of some kind passed into the function evaluation either implicitly (via mesh variables that are defined using a coordinate system) or explicitly so we know which unknowns in a sympy expression are the coordinate vectors that are referred to in the coordinates argument. We could eliminate that by adding a coordinate object that is an array plus the definition of the coordinate entries.

**Comment by lmoresi** [comment]
Oh, and I also added a handle to the mesh on the symbolic form of the mesh variable (var.sym now has var.sym.mesh) so that we can ask about coordinates etc in evaluations. That feels like a temporary fix while we work out what to do ...

**Comment by lmoresi** [comment]
To add to the cylindrical coordinate implementation, I threw together (i.e. not yet well tested) the spherical equivalent. This is implemented in r, lon, lat coordinates (slightly different from the standard math / physics choices, but maybe more logical for  planets). I did this as part of a tidy up - I added the infinitesimal strain definition to the vector calculus section as this completely geometrical and keeps the solvers clean.

The meshing choices are a bit limited because dmplex periodicity does not really enjoy having to deal with nodes that lie exactly on the axis and gmsh seems to do this by default when constructing circles / spheres (not hard to fix, but annoying)
However, it does work with the simplex version of the cubed sphere if the element number is odd. We'll see if we can actually solve !

Also fixed up the constitutive equation examples so I can validate the Transverse Isotropy implementation.

Tests passing / trivial parallel tests passing.

**Comment by lmoresi** [comment]
Lots of tidying - ready to merge into dev

**Pull request merged**
