### PR TITLE
Fix pyvista issue while saving a screenshot

### PR DESCRIPTION
**Pull request by gthyagi**
I resolved the problem with saving the screenshot image as a PNG. Instead of using `client`, I set `pv.global_theme.jupyter_backend` to `"trame"`.

### CODE REVIEW

**Comment by lmoresi** [comment]
OK - looks fine to me. We'll need to look at what happens on binder which is what drove this change.

**Comment by julesghub** [comment]
wow - that was a big PR. All the Notebooks vanished. 
This needs to be reflected in the README asap.

**Comment by gthyagi** [comment]
Same issue, could not see Example Notebooks in the binder.

**Comment by gthyagi** [comment]
@lmoresi In binder, pyvista throws segfault if `pv.global_theme.jupyter_backend = "trame"` and it works fine with `client`

**Comment by gthyagi** [comment]
Is it possible to check whether the Notebook is running in binder or not? Then set backend option accordingly

**Pull request merged**
