### PR TITLE
2022 03 02 lm updates

### PR DESCRIPTION
**Pull request by lmoresi**

### CODE REVIEW

**Comment by julesghub** [comment]
@lmoresi  `Ex_Poisson_Gradient_Recovery.py` is busted on this branch.
Is that expected?

**Comment by julesghub** [comment]
I fixed a problem with the `Projection()` initialiser now I'm getting at error re:
'SNES_Projection' object has no attribute '_uw_function'

Thoughts?

**Comment by lmoresi** [comment]
Hi @julesghub ... 

Yes, that error. I should fix this in the example notebook but I was talking about this the other day. We have this pattern, partly inherited from John and partly from uw2 that we make the solver and then populate it ... i.e. we don't check to see at init time if everything we need is present. We do this with stokes and poisson too but not for everything. I'm a bit concerned that this creates hard-to-find errors but it needs us to think it through.

**Comment by julesghub** [comment]
Ok please fix in the notebook and then we can discuss a general approach for catching these 'under defined' systems.

**Comment by lmoresi** [comment]
The projector class accepts `uw_function` rather than the previous behaviour of loading a RHS that is (u-uw_function). We'd best get the tests working to catch all my regressions. 

This notebook still fails on a numerical accuracy test. I'm not sure how to fix that. The regular hex mesh is great, but all the others seem to have errors at the 1% level.

**Comment by julesghub** [comment]
Thanks for the quick fix. Yes the regressions are getting troublesome to keep up with! I think `git rebase` is your friend if using multiple branches but your the only one developing on one. Give that a go in future.

Failing on numerical accuracy? Interesting. Could we test via convergence behaviour?

**Comment by lmoresi** [comment]
Agreed, Jules ... rebase it is. 

As for testing, yes, it's worth looking a different strategies but right now, we probably want to focus on actual bug regression until we have had a crack at benchmarking because we won't really know what / why things are going awry.

**Pull request merged**
