### PR TITLE
adding mpicc system path of setup.py

### PR DESCRIPTION
**Pull request by gthyagi**
Hi,

I've updated the `setup.py` file to retrieve `mpicc` from the system-wide installation instead of relying only on the environment installation.

### CODE REVIEW

**Comment by gthyagi** [comment]
#242, issue reported here.

**Comment by gthyagi** [comment]
The reason for issue #242 is that `mpi4py version 4` does not provide the necessary path information when calling `get_config()`. For more details and potential solutions, please refer to the discussion in this GitHub issue: 
 https://github.com/mpi4py/mpi4py/issues/532

**Comment by julesghub** [comment]
@gthyagi, looking at this more it doesn't seem like we need to even use environ["CC"] anywhere. Can you confirm?

If the code is obsolete let's remove it.

**Comment by gthyagi** [comment]
@julesghub yes, we can remove these lines from the `setup.py` file. https://github.com/underworldcode/underworld3/blob/372ecce37d1867266471c4d60b6dcf47770f12e9/setup.py#L13-L34

**Comment by julesghub** [comment]
ok, then I'll close this PR and I will make a new one to remove

**Pull request closed without merging**
