### PR TITLE
Bk may constitutive model updates

### PR DESCRIPTION
**Pull request by julesghub**
1. Added a pytest with a pic sensitive stokes solve.
2. Merged in non-breaking changes from the Mask2Matrix branch. Still mask variables are NOT a matrix as discussed.

### CODE REVIEW

**Review by lmoresi — COMMENTED** [review]
Shouldn't it be

```
            shear_viscosity_min: Union[list, sympy.Function] = [+sympy.oo],
            shear_viscosity_max: Union[list, sympy.Function] = [-sympy.oo],

```
so that sympy can correctly simplify a Min(+sympy.oo, x) to x ?

**Comment by bknight1** [comment]
I think it's correct as you want to use Max(shear_viscosity_min, x) and Min(shear_viscosity_max, x)

```
shear_viscosity_min = [-sympy.oo]
shear_viscosity_max = [sympy.oo]
shear_viscosity_0  = [1.]

effective_viscosity = sympy.Min(shear_viscosity_max[0], sympy.Max(shear_viscosity_min[0], shear_viscosity_0[0]) ) 
```

**Comment by lmoresi** [comment]
Ah ok - for once the sympy cleverness makes things confusing

**Comment by bknight1** [comment]
If we want to add plastic strain weakening to the VP constitutive model we might want to add a plastic_viscosity property to make it easy to determine where yielding is occurring (where plastic_viscosity <  viscosity)

**Comment by julesghub** [comment]
@bknight1 is implementing the ViscoElasticPlasticFlowModel, then we will merge this PR into dev.
After that we will rebase the #127 with 'development'

**Pull request merged**
