### PR TITLE
Prototype of an index swarm "solution" to particle in cell integration

### PR DESCRIPTION
**Pull request by lmoresi**
I have introduced a new swarm class: `IndexSwarmVariable` which is an integer swarm variable which plays the role of a material index. In place of the usual proxy variable, there is a collection of proxies each of which is a 0.0 -> 1.0 mask for one of the index values. This is handled automatically by the `_update` method.

For a variable $M$, the mask variables are $\left( M^0, M^1, M^2 \ldots M^{N-1} \right)$ where $N$ is the number of indices (e.g. material types) on the variable. This value *must be defined in advance*.

The masks are orthogonal in the sense that $M^i * M^j = 0$ if $i \ne j$, and they are complete in the sense that $\sum_i M^i = 1$ at all points. 

The masks are implemented as continuous mesh variables (the user can specify the interpolation order) and so they are also differentiable (once). 

---

We don't currently have a good strategy for indexing multi-component variables, so I have introduced one that is based on `sympy.tensor` (which we use in the solver internals).  In addition to the usual `variable.fn`, I have introduced a `variable.f` which is a sympy tensor and could naturally be extended to hold symbolic forms of the strain rate etc like the ones we use in the solvers. 

We therefore have the following 

```python
swarm     = uw.swarm.Swarm(mesh=meshbox)
material = uw.swarm.IndexSwarmVariable("M", swarm, indices=4)
swarm.populate(fill_param=4)

# Define the material values somewhere 

...

mat_viscosity = np.array([1,0.1,10.0,10.0])
viscosity = mat_viscosity[0] * material.f[0] + \
            mat_viscosity[1] * material.f[1] + \
            mat_viscosity[2] * material.f[2] + \
            mat_viscosity[3] * material.f[3] 
```
blobs_step_25

**NOTE:** the current vector function implementation works well as long as the vectors represent spatial fields. If we want the first component, we do `v.fn.dot(mesh.N.i)` but that doesn't work for arbitrary length vectors. I have added the `.f` to all variables and (worry, worry), I have also had to change the JIT code to use this. There are some rough edges, but I think it will eventually make the code cleaner. 

I don't have examples for that part yet, but there is a quick demo in `Ex_Swarm_Bubbles.py`

### CODE REVIEW

**Comment by rbeucher** [comment]
Great! I think I have a way around the batman style set up. 
The `IndexSwarmVariable` is an int variable. We could get the unique index values when the field is initialized and create the masks accordingly. 

The demo is good but we need tests and we also need to decide on how this is going to be used at a user level.

I think we should finalize this asap.

**Comment by lmoresi** [comment]
Thanks @rbeucher.

Yes to the masks - I think what you are saying is that the number of indices would be chosen on the fly to match the unique-values in the array (so no need even to make them consecutive). As long as we can define more variables after setting values. 

I think that a fix for batman is a great thing to do because it also means that we can define everything for a particular solver in one block. At the moment, we have to break them all up and be very careful with solvers like Navier-Stokes that rely on creating their own swarm variables behind the scenes. 

As for examples, this one is just a demo - but we already have a bunch of RT benchmarks that we need to implement and I suggest that we grab those and start coding. I would like to get this sorted and start writing it into the uw3 paper.

**Comment by rbeucher** [comment]
It is not just the index swarm implementation in that PR. I see a lot of changes on the solver. it's not related, is it?

**Comment by lmoresi** [comment]
It's not completely unrelated because I had to change a couple of things in the way the functions are interpreted in the JIT etc I found problems with the quadrature that I tried to sort out.

**Comment by julesghub** [comment]
> It is not just the index swarm implementation in that PR. I see a lot of changes on the solver. it's not related, is it?

I agree - would be nice to break up the Saddle solve commits with the `.f` solution. 

Test are needed before we accept this. I few sanity tests of the IndexSwarm and some stokes solves using it.

**Comment by jmansour** [comment]
Yeah I think this is the correct solution here, given that everything needs to operate through a continuous variable proxy (and rounding to integers won't give reliable results).

Is orthogonality required? You could otherwise have materials that are represented as compositions of other materials via some choice of averaging.

**Comment by lmoresi** [comment]
Ok - so I think the .f stuff has to be done first because the index Swarm depends on those changes. 

I implemented this after the fact, but I can go back and re-implement into dev first and commit those changes first. I think that I would like to use the matrix type rather than ndarray as it is more flexible and easier to use for everything except manipulation of tensors of rank 3 and above.

So if I do that, make a pull request, and see what you think. I guess we really need anisotropic constitutive behaviour if we want to test that properly. I'll see how I go.

**Comment by lmoresi** [comment]
To @jmansour - the orthogonality may not be required but it is what you want to happen with the nodal variables at the nodes themselves. There will be some overlap at the integration points I think though.

**Comment by rbeucher** [comment]
OK, How do we merge this @lmoresi. How can I help?

**Comment by lmoresi** [comment]
I'm going to split this as requested: do the .f stuff as one PR for review first, then add the indexing stuff.

**Pull request closed without merging**
