### PR TITLE
conda fix

### PR DESCRIPTION
**Pull request by julesghub**
Need to test build on mac's, i.e arm architecture.

### CODE REVIEW

**Comment by bknight1** [comment]
I recently built dev on mac (~3 days ago) using conda, everything was running okay

**Comment by julesghub** [comment]
@bknight1 nice one! I'm having troubles with it, specifically petsc4py. Can you share your recipe on mac?

**Comment by bknight1** [comment]
I used this yml file to create the conda/mamba env:
https://github.com/underworldcode/underworld3/blob/development/.github/workflows/envs/build_uw_test.yml

then installed from a pull of the dev branch using:
`python3 setup.py develop`

**Comment by julesghub** [comment]
Thanks for that, I'm using petsc4py-3.21.2 and finding liblapack/openblas dylib errors.

**Comment by julesghub** [comment]
Magic something in the file you linked to fixes the issue. The dependencies cause a different liblapack / libopenblas combination that fixes the error. :magic_wand:

**Pull request merged**
