### PR TITLE
Updates feb21 2022

### PR DESCRIPTION
**Pull request by lmoresi**
This is a slew of stuff:

  - a little bit of a write-up in the jupyterbook showing how the PETScDS and sympy align
  - All the projectors that we need for solvers, and in particular:
    - Projection with boundary conditions that match the advection-diffusion fields and their particle equivalents
    - Same but with incompressibility for the navier-stokes equation
  - Swarm advection / parallel with correction term
  - Callback function to hunt down vagrant particles
  - Adv.diff and Navier-Stokes are implemented using swarms for the advection part and projection to map to nodes. These are managed by the solvers themselves so that they can load the correct boundary conditions for the projection

What is missing ?
  - Population control. In particular, the projection from swarm to mesh becomes less and less accurate for NS even though it remains stable. Need to re-populate the swarm near to stagnation points (and prune elsewhere, though this is an efficiency question not an accuracy one). This is the "benchmark" we want to run and there is a lot of additional diffusion because the particles are patchy in the vortex train.
Vortex
  - Viscoelasticity / Anisotropy / 
  - Adding a standard location for constraint terms so that the projection operators in N-S and Adv-Diff can copy them from the parent.

### CODE REVIEW

**Comment by knepley** [comment]
@lmoresi I was thinking about this. I think we could use the same projection technology to adapt a swarm, with FEM as an intermediary. After projecting from particles to FEM, we can project back to a different set of particles which are enriched in the sparse areas. What is needed is a good particle error estimator. Varis Carey is supposed to talk on this on Saturday, so I will see what I can learn.

**Comment by rbeucher** [comment]
@knepley we were thinking something along those lines. Would be good to hear your ideas!

**Comment by lmoresi** [comment]
@knepley - yes, the FE projection seems very powerful, especially since we can include boundary conditions and constraints. This seems to me to have been one of the arm-waving areas of the various PIC approaches in the past.

What are your thoughts on piecewise continuous functions for the pint wise approach ? What we currently do with swarms feels like a workaround. We would like to build projections, as above, but the integrals to project swarm values to mesh fields are constructed in a way that is not part of the standard approach in petscDS ... what are your thoughts ?

**Comment by rbeucher** [comment]
I am merging this. I have opened an issue #57 so we can discuss implementing efficient Population Control.

**Pull request merged**
