### PR TITLE
Constitutive model updates

### PR DESCRIPTION
**Pull request by lmoresi**
This branch is getting a bit heavy and we should probably use this is the starting point towards an alpha release.

  - Constitutive models: there is a framework in place to split off constitutive behaviour from specific solvers
  - Coordinate systems: I put in some scaffolding for where the symbolic operations for natural mesh coordinates should go. There are some things here like defining "vertical" which make it easy to write general expressions in symbolic form for the rotated boundary conditions as penalties or constraints.
  - Jacobians / sympy: *oh the indexing horrorshow !!* I think we can generalise this nicely quite soon but it does need some insider work. I suggest we leave this alone until we have some benchmarking done. Seems to be working now though: the solvers are pretty robust.
  - Quadrature: this got out of hand a bit and we did a lot of tinkering behind the scenes. I made this an explicit mesh property and we can warn users if they are acting inconsistently.
  - Material indexing swarms - fixed up a few odds and ends. I'd like element-wise discontinuous linear interpolants for testing purposes but the coordinates overlap in a way that is not helpful for our kdtree implementation.
  - de-cythonisation as much as possible by 1) using latest petsc4py wrapped functions, and 2) moving cython-dependent functions out of otherwise pure-python modules.
  
I also fixed up a bunch of stuff:

 - Poisson notebooks are OK & Poisson tests
 - Stokes notebooks: I cut them down and got most of them working. RT is a work in progress. Spherical examples are quite clean now, and maybe the penalty boundary conditions are not so ugly after all (I think there was an indexing bug in that section of the Jacobian that is now fixed). 
 - Darcy benchmark is OK, some snes tolerance naughtiness. 
 
Release-oriented stuff:
  
 - Added pdoc3 scripts and 
   - configured for markdown docstrings
   - added some _ipython_display circuitry for processing the (pdoc3) markdown docstrings to make them mostly compatible with notebooks. WIP on that one but could be good.
 - Added pyproject.toml and configs for:
   - setup.py (including build-in-place with pip and not deleting the entire directory!)
   - black for formatting consistency
   - pytest

### CODE REVIEW

**Comment by julesghub** [comment]
I'm seeing lots of:
```
underworld3/discretisation.py:210: in nuke_coords_and_rebuild
    self.dm.projectCoordinates(self.petsc_fe)
E   AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'projectCoordinates
```
I'm using petsc-3.17.4. What are you using @lmoresi?

**Comment by bknight1** [comment]
@julesghub I had the same issue, you'll have to pull the latest version of petsc from their github then install the petsc bindings using pip3 install . in the src/bindings/petsc4py directory. Should be 3.18.0---dev or something along those lines

**Comment by bknight1** [comment]
Unable to recompile from scratch, issue with finding Cython during install although it's installed. Can't see any obvious changes in setup but will dig deeper.

**Comment by julesghub** [comment]
Use `python setup.py build_ext` instead of `pip3 install -e .`

**Comment by lmoresi** [comment]
The pyproject.toml approach needs a bit of thought and it's not clear that pip -e is actually supported. Julian's approach might be the best thing for development.

I'm using the bleeding edge petsc from a couple of weeks ago.

**Comment by jmansour** [comment]
Wow, looks like huge progress here guys!  Amazing! 👏👏

I've been out of the loop for a while, but if there's anything in particular where you think I might be able to assist, please do let me know. 

I'm going to pull this down and have a play. What's the status of building on Apple Silicon?

**Comment by lmoresi** [comment]
Apple build is fine but the path is quite specific and we really do need bleeding edge petsc to make it work. Ben knight did this most recently!

L

Sent from my iPhone

On 10 Sep 2022, at 12:03 am, John Mansour ***@***.***> wrote:

﻿

Wow, looks like huge progress here guys! Amazing! 👏👏

I've been out of the loop for a while, but if there's anything in particular where you think I might be able to assist, please do let me know.

I'm going to pull this down and have a play. What's the status of building on Apple Silicon?

**Comment by bknight1** [comment]
It should be okay to build on apple silicon, these steps should work. Let me know if you run into any issues so we can keep it up to date. Cheers

[UW3_install_guide.txt](https://github.com/underworldcode/underworld3/files/9539342/UW3_install_guide.txt)

**Comment by jmansour** [comment]
Thanks @bknight1 

I'm having a play with Spack to see if that's a viable path for the M1 build, but there are difficulties around Fortran which is required (it seems) for `openmpi` (along with other deps too).  I'll refer to your notes and share useful discoveries (if there are any 🙂).

**Comment by julesghub** [comment]
Just fixed it @bknight1

**Comment by bknight1** [comment]
After fix getting the following: `AttributeError: partially initialized module 'underworld3' has no attribute 'discretisation' (most likely due to a circular import)` reverting back to the original _fuction.pyx file seems to work

**Comment by lmoresi** [comment]
We've been through a number of reviews on this one and there may still be some design flaws and bugs in parallel that we have not chased down. However, this is more mature than the development branch and more reliable so we will merge it in now.

**Pull request merged**
