### PR TITLE
'pip install -e .'

### PR DESCRIPTION
**Pull request by julesghub**
Using pip to install dependencies and build uw3. This will replace
`python setup.py build_ext --inplace`

### CODE REVIEW

**Comment by julesghub** [comment]
@rbeucher, not sure if this causes issues with conda. Please let me know what you think.

**Comment by julesghub** [comment]
Actually something is busted with this. I think the compile or link options from petsc are causing incompatibility for resolving symbols. Need to investigate more.

**Comment by jmansour** [comment]
@julesghub I'm still a bit confused about the purpose of `-e` here.  

For developers, I think `python setup.py build_ext --inplace` is still the right build strategy as it's reasonably fast.  

For users, just the usual `pip install .` should be what they want right? The editable mode with pip isn't much use cos Cython right?

**Review by rbeucher — APPROVED** [review]
I'm not sure this is going to be portable....
Let's see.

**Pull request merged**
