### PR TITLE
Free surface meshes

### PR DESCRIPTION
**Pull request by julesghub**
Louis' PR for review

### CODE REVIEW

**Comment by knepley** [comment]
I can't find the code for "mesh integrals". Do these use DMPlexIntegrate()? If not, can I make that better so that it will do what you want?

**Comment by jmansour** [comment]
Hi @knepley 

I'm not sure if @lmoresi has something different in there now, but this was my implementation.

https://github.com/underworldcode/underworld3/blob/Free-surface-meshes/underworld3/maths.pyx

**Comment by knepley** [comment]
Cool, that is exactly what I was thinking.

**Comment by lmoresi** [comment]
> Hi @knepley
> 
> I'm not sure if @lmoresi has something different in there now, but this was my implementation.
> 
> https://github.com/underworldcode/underworld3/blob/Free-surface-meshes/underworld3/maths.pyx

Yep, that's all good, John, I missed a few things ...

**Pull request merged**
