### PR TITLE
Labelling work around

### PR DESCRIPTION
**Pull request by lmoresi**
[Not sure why this PR is so far from DEV - just one commit that addresses the following]

> The surface integral code falls over if a label is not present on one of the processes (including having one label with many values - if the segment of the boundary with a particular value is not present, the code hangs). This is identified in issue #240 

This workaround adds element-volumes (all of them) to each boundary label. These are not used in the surface integral code in 2D / 3D so they do not change the result. @knepley  - we've discussed this issue in the past ... we should figure out the actual origin of the problem but, if this fix is not too dangerous, it keeps us from needed a bespoke PETSc build.

### CODE REVIEW

**Comment by lmoresi** [comment]
I forgot to mention: tests passing, and also @gthyagi 's parallel unit test produces consistent results in serial, parallel with and without this fix ('cept not the parallel without which doesn't run, obviously)

**Comment by gthyagi** [comment]
@lmoresi The labeling workaround worked on my Mac and with the simple example. I'm currently testing the branch on NCI and will review the PR afterward.

**Comment by gthyagi** [comment]
@lmoresi The labeling workaround works correctly when no internal boundary is present, with L2 norms being the same in both parallel and serial runs. However, when an internal boundary is introduced, the L2 norm for velocity differs between serial and parallel runs.

Serial results:
```
L2 norm in velocity :  0.006840571977819887
L2 norm in pressure :  0.1822894341606508
```

Parallel results:
```
L2 norm in velocity :  0.013286955225573976
L2 norm in pressure :  0.1844758437641978
```

Here is the annulus benchmark script I ran:
https://github.com/underworldcode/underworld3-documentation/blob/main/Jupyterbook/Notebooks/Examples-Annulus-Stokes/Ex_Stokes_Annulus_Benchmark_Kramer.py

mpirun -np 8 python Ex_Stokes_Annulus_Benchmark_Kramer.py

res = 16

case1 has internal boundary and case2 has no internal boundary

**Comment by lmoresi** [comment]
That's not entirely surprising, we can try to be a bit more clever ... it's a start that we can deal with actual boundaries !

**Comment by gthyagi** [comment]
Okay. For the sphere with an internal boundary, it seems the code is still hanging at the Stokes solve.

```
SNES solve - picard = 0
    Residual norms for stokes_ solve.
    0 KSP Residual norm 2.008253432829e+06
```

**Comment by gthyagi** [comment]
Even with the new change, L2 norm in velocity is different in serial and parallel runs.

**Comment by lmoresi** [comment]
Maybe it's worth checking the 2D benchmarks first.

**Comment by gthyagi** [comment]
Currently, I am testing only on the annulus benchmarks.

**Comment by lmoresi** [comment]
OK - thing to check is whether the parallel runs are different for cases where the labelling is an issue v. those where it is not. This would help with the debugging. If no label has zero representation on the mesh, then no adjustments are made.  That's a lot of negatives in one sentence. I mean that it only makes changes in the case where a label does not appear everywhere.

**Comment by gthyagi** [comment]
I will create debug tests to understand what is happening.

**Comment by gthyagi** [comment]
The recent changes seem to be working!

Serial run
```
L2 norm in velocity:  0.006840571977819887
L2 norm in pressure:  0.1822894341606508
```

Parallel run
```
L2 norm in velocity:  0.006840571977880224
L2 norm in pressure:  0.18228621657479746
```

**Comment by gthyagi** [comment]
~~This is also seems to be working.~~

Oops, labeling all edges isn't working as expected.

**Pull request merged**
