### PR TITLE
Development

### PR DESCRIPTION
**Pull request by lmoresi**
Current Dev branch needs to become the 1.0 release for main, (or 3.0 if we want to be consistent with underworld 1 and 2)

This is the last major thing in the way of the JOSS release. If there are further bugs, they can be fixed as we find them, but we really need to be in a position to tidy the code and get it reviewed ASAP.

### CODE REVIEW

**Comment by lmoresi** [comment]
Sorry, that last commit was trying to fix #205 - I don't think it will do anything for the others.

**Comment by lmoresi** [comment]
@gthyagi — can you check to see if the surface-integral workaround in my recent commit does the job. It seems to work for me - I'm adding a fictitious natural bc (automatically) that appears on all the decomposed nodes but (mathematically) does nothing

**Comment by gthyagi** [comment]
> @gthyagi — can you check to see if the surface-integral workaround in my recent commit does the job. It seems to work for me - I'm adding a fictitious natural bc (automatically) that appears on all the decomposed nodes but (mathematically) does nothing

Recent changes yield consistent results for meshes without internal boundary, but the results are still inconsistent when internal boundary is present.
 
```
Serial run
(36, -0.0, -0.403867, 0.403867, -0.0, 0.838121, np.float64(0.139687))

mpirun -np 2 python Natural_BC_Bug_with_Int_BD.py
(36, -0.0001, -0.403967, 0.403768, -0.003584, 0.838121, np.float64(0.139687))

mpirun -np 4 python Natural_BC_Bug_with_Int_BD.py 
(36, -0.007265, -0.526843, 0.512313, -0.261537, 1.190362, np.float64(0.198394))

mpirun -np 10 python Natural_BC_Bug_with_Int_BD.py
(36, 0.006844, -0.588039, 0.522585, 0.24637, 1.058837, np.float64(0.176473))
```

**Review by bknight1 — APPROVED** [review]
Don't see any major issues as most people are running models on dev anyway

**Pull request merged**
